name: Run main sync script

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "22 0/8 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install system dependencies
      run: apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:git-core/ppa && apt-get update && apt-get install -y git build-essential clang libssl-dev libkrb5-dev libc++-dev wget
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Setup python 3.6
      env:
        CC: clang
        CXX: clang++
      run: |
          mkdir ~/python
          cd ~/python
          wget https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz
          tar -xvf Python-3.6.15.tgz
          cd Python-3.6.15
          ./configure
          make
          make install

    - name: Install node dependencies
      run: npm i

    - name: Run main sync script
      run: |
          mkdir ~/tmp_repo
          npm run start
      env:
        GITLAB_USERNAME: ${{secrets.GITLAB_USERNAME}}
        GIT_USERNAME: ${{secrets.GIT_USERNAME}}
        GIT_EMAIL: ${{secrets.GIT_EMAIL}}
        FAKE_COMMITS_REPO_URL: ${{secrets.FAKE_COMMITS_REPO_URL}}
        FAKE_COMMITS_REPO_DEPLOY_KEY_PUBLIC: ${{secrets.FAKE_COMMITS_REPO_DEPLOY_KEY_PUBLIC}}
        FAKE_COMMITS_REPO_DEPLOY_KEY_PRIVATE: ${{secrets.FAKE_COMMITS_REPO_DEPLOY_KEY_PRIVATE}}
